name: Trigger auto deployment for airesume-backend

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ firebase-integration ]
    paths:
    - '**'
    - '.github/workflows/airesume-backend-AutoDeployTrigger-c42f2151-7a07-4d95-88a8-0aaafd8d87ed.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AIRESUMEBACKEND_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AIRESUMEBACKEND_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AIRESUMEBACKEND_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: 
          registryUsername: ${{ secrets.AIRESUMEBACKEND_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.AIRESUMEBACKEND_REGISTRY_PASSWORD }}
          containerAppName: airesume-backend
          resourceGroup: AIResume
          imageToBuild: default/[parameters('containerAppName')]:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


